version: '3.5'

services:
  db:
    image: postgres
  web:
    build:
      context: ../
      dockerfile: Dockerfile.dev
    command: ./scripts/start.sh
    volumes:
      - ../:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: 'config.settings.local-docker'