version: '3.5'

services:
  db:
    image: postgres
  web:
    build:
      context: ../
      dockerfile: Dockerfile.dev
    image: registry.cn-shenzhen.aliyuncs.com/ash-workshop/drf-starter:latest
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../:/code
    ports:
      - "8000:8000"
    depends_on:
      - db