version: '3.5'

services:
  db:
    image: postgres
  web:
    image: registry.cn-shenzhen.aliyuncs.com/ash-workshop/drf-starter:latest
    command: ./scripts/start.sh
    volumes:
      - ../:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: 'config.settings.local-docker'